[define]
"target_os=null" = "??"
"target_pointer_width=64" = "__LP64__"
"target_pointer_width=32" = "__LP32__"
"target_arch=x86_64" = "__x86_64__"

"feature = no_std" = "__libl__"

[fn]
must_use = "__nodiscard"
deprecated = "__deprecated"
deprecated_with_note = "__deprecateNote({})"
no_return = "__noreturn"
