entry:

	@r1 mov <M> @type ^
	mov 0x0000 <> ^@r4
	@r3, @r1  <N @push?> 
	mov @r7 @r1(+9)

	Mv> UU><2 @r3 @e1
	mov @r6, M(in @r1)
	call @r2 *@main ^M
	push M
	jrk @r8(@r6 / 0_3) ^r && @r3
	jmp @r2, @r1(@r5 + 0_1) <mov M @r1>
	sec <M ^@r1 *main 
	
	ldr @r11, *block
	mov *block, @r12

	mov @r12, movk x11
	cmp x11 (
	mov x12, x22 
	movk x21 x15
	cmp *x 8
	null ^u16 )
	movk @r3 (j)
	M9
	@r1 ^@r5(*main u8) 
	push @r6, ^M
	push @main
